# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\admin\Documents\works\camera\Statics\add.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AddWindow(object):
    def setupUi(self, AddWindow):
        AddWindow.setObjectName("AddWindow")
        AddWindow.resize(324, 300)
        self.btn_submit = QtWidgets.QDialogButtonBox(AddWindow)
        self.btn_submit.setGeometry(QtCore.QRect(20, 260, 281, 32))
        self.btn_submit.setOrientation(QtCore.Qt.Horizontal)
        self.btn_submit.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.btn_submit.setObjectName("btn_submit")
        self.formLayoutWidget = QtWidgets.QWidget(AddWindow)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 30, 281, 231))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.from_camera = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.from_camera.setContentsMargins(0, 0, 0, 0)
        self.from_camera.setObjectName("from_camera")
        self.Label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.Label_6.setObjectName("Label_6")
        self.from_camera.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_6)
        self.box_name = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.box_name.setObjectName("box_name")
        self.from_camera.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.box_name)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.from_camera.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.box_sn = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.box_sn.setObjectName("box_sn")
        self.from_camera.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.box_sn)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.from_camera.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.box_address = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.box_address.setObjectName("box_address")
        self.from_camera.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.box_address)
        self.sDKLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.sDKLabel.setObjectName("sDKLabel")
        self.from_camera.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.sDKLabel)
        self.box_action_type = QtWidgets.QComboBox(self.formLayoutWidget)
        self.box_action_type.setObjectName("box_action_type")
        self.box_action_type.addItem("")
        self.box_action_type.addItem("")
        self.from_camera.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.box_action_type)
        self.Label = QtWidgets.QLabel(self.formLayoutWidget)
        self.Label.setObjectName("Label")
        self.from_camera.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Label)
        self.box_user_name = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.box_user_name.setObjectName("box_user_name")
        self.from_camera.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.box_user_name)
        self.Label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.Label_2.setObjectName("Label_2")
        self.from_camera.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.Label_2)
        self.box_password = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.box_password.setObjectName("box_password")
        self.from_camera.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.box_password)
        self.Label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.Label_3.setObjectName("Label_3")
        self.from_camera.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.Label_3)
        self.box_kind = QtWidgets.QComboBox(self.formLayoutWidget)
        self.box_kind.setEditable(True)
        self.box_kind.setObjectName("box_kind")
        self.box_kind.addItem("")
        self.from_camera.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.box_kind)
        self.Label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.Label_4.setObjectName("Label_4")
        self.from_camera.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.Label_4)
        self.box_brand = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.box_brand.setObjectName("box_brand")
        self.from_camera.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.box_brand)
        self.Label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.Label_5.setObjectName("Label_5")
        self.from_camera.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.Label_5)
        self.box_model = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.box_model.setObjectName("box_model")
        self.from_camera.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.box_model)

        self.retranslateUi(AddWindow)
        self.box_action_type.setCurrentIndex(0)
        self.box_kind.setCurrentIndex(-1)
        self.btn_submit.accepted.connect(AddWindow.accept)
        self.btn_submit.rejected.connect(AddWindow.reject)
        QtCore.QMetaObject.connectSlotsByName(AddWindow)

    def retranslateUi(self, AddWindow):
        _translate = QtCore.QCoreApplication.translate
        AddWindow.setWindowTitle(_translate("AddWindow", "添加设备"))
        self.Label_6.setText(_translate("AddWindow", "名称"))
        self.box_name.setPlaceholderText(_translate("AddWindow", "必填项，可填写任意内容"))
        self.label.setText(_translate("AddWindow", "SN编号"))
        self.box_sn.setPlaceholderText(_translate("AddWindow", "必填项"))
        self.label_2.setText(_translate("AddWindow", "IP地址"))
        self.box_address.setPlaceholderText(_translate("AddWindow", "必填项"))
        self.sDKLabel.setText(_translate("AddWindow", "SDK类型"))
        self.box_action_type.setItemText(0, _translate("AddWindow", "海康α"))
        self.box_action_type.setItemText(1, _translate("AddWindow", "海康β"))
        self.Label.setText(_translate("AddWindow", "登录名"))
        self.box_user_name.setPlaceholderText(_translate("AddWindow", "必填项"))
        self.Label_2.setText(_translate("AddWindow", "密码"))
        self.box_password.setPlaceholderText(_translate("AddWindow", "必填项"))
        self.Label_3.setText(_translate("AddWindow", "种类"))
        self.box_kind.setItemText(0, _translate("AddWindow", "摄像头"))
        self.Label_4.setText(_translate("AddWindow", "品牌"))
        self.Label_5.setText(_translate("AddWindow", "型号"))

