# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\admin\Documents\works\camera\Statics\camera.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(791, 551)
        MainWindow.setMinimumSize(QtCore.QSize(791, 551))
        MainWindow.setMaximumSize(QtCore.QSize(791, 551))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gBox_action = QtWidgets.QGroupBox(self.centralwidget)
        self.gBox_action.setGeometry(QtCore.QRect(350, 320, 441, 211))
        self.gBox_action.setObjectName("gBox_action")
        self.tab_action = QtWidgets.QTabWidget(self.gBox_action)
        self.tab_action.setGeometry(QtCore.QRect(10, 20, 421, 181))
        self.tab_action.setTabPosition(QtWidgets.QTabWidget.West)
        self.tab_action.setObjectName("tab_action")
        self.tab_action_sample = QtWidgets.QWidget()
        self.tab_action_sample.setObjectName("tab_action_sample")
        self.tab_action.addTab(self.tab_action_sample, "")
        self.tab_action_multi = QtWidgets.QWidget()
        self.tab_action_multi.setObjectName("tab_action_multi")
        self.tab_action.addTab(self.tab_action_multi, "")
        self.gBox_list = QtWidgets.QGroupBox(self.centralwidget)
        self.gBox_list.setGeometry(QtCore.QRect(0, 0, 351, 531))
        self.gBox_list.setObjectName("gBox_list")
        self.list_camera = QtWidgets.QListView(self.gBox_list)
        self.list_camera.setGeometry(QtCore.QRect(10, 20, 331, 501))
        self.list_camera.setObjectName("list_camera")
        self.gBox_info = QtWidgets.QGroupBox(self.centralwidget)
        self.gBox_info.setGeometry(QtCore.QRect(350, 0, 441, 321))
        self.gBox_info.setObjectName("gBox_info")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.gBox_info)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 421, 291))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.from_camera_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.from_camera_2.setContentsMargins(0, 0, 0, 0)
        self.from_camera_2.setObjectName("from_camera_2")
        self.Label_12 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.Label_12.setObjectName("Label_12")
        self.from_camera_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_12)
        self.box_name = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.box_name.setReadOnly(True)
        self.box_name.setObjectName("box_name")
        self.from_camera_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.box_name)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.from_camera_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.box_sn = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.box_sn.setReadOnly(True)
        self.box_sn.setPlaceholderText("")
        self.box_sn.setObjectName("box_sn")
        self.from_camera_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.box_sn)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.from_camera_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.box_address = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.box_address.setReadOnly(True)
        self.box_address.setPlaceholderText("")
        self.box_address.setObjectName("box_address")
        self.from_camera_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.box_address)
        self.sDKLabel_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.sDKLabel_2.setObjectName("sDKLabel_2")
        self.from_camera_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.sDKLabel_2)
        self.box_action_type = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.box_action_type.setReadOnly(True)
        self.box_action_type.setPlaceholderText("")
        self.box_action_type.setObjectName("box_action_type")
        self.from_camera_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.box_action_type)
        self.Label_7 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.Label_7.setObjectName("Label_7")
        self.from_camera_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Label_7)
        self.box_user_name = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.box_user_name.setReadOnly(True)
        self.box_user_name.setPlaceholderText("")
        self.box_user_name.setObjectName("box_user_name")
        self.from_camera_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.box_user_name)
        self.Label_8 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.Label_8.setObjectName("Label_8")
        self.from_camera_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.Label_8)
        self.box_password = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.box_password.setReadOnly(True)
        self.box_password.setPlaceholderText("")
        self.box_password.setObjectName("box_password")
        self.from_camera_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.box_password)
        self.Label_9 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.Label_9.setObjectName("Label_9")
        self.from_camera_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.Label_9)
        self.box_kind = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.box_kind.setReadOnly(True)
        self.box_kind.setPlaceholderText("")
        self.box_kind.setObjectName("box_kind")
        self.from_camera_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.box_kind)
        self.Label_10 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.Label_10.setObjectName("Label_10")
        self.from_camera_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.Label_10)
        self.box_brand = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.box_brand.setReadOnly(True)
        self.box_brand.setObjectName("box_brand")
        self.from_camera_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.box_brand)
        self.Label_11 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.Label_11.setObjectName("Label_11")
        self.from_camera_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.Label_11)
        self.box_model = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.box_model.setReadOnly(True)
        self.box_model.setObjectName("box_model")
        self.from_camera_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.box_model)
        self.rTMPLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.rTMPLabel.setObjectName("rTMPLabel")
        self.from_camera_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.rTMPLabel)
        self.btn_rtmp1 = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.btn_rtmp1.setObjectName("btn_rtmp1")
        self.from_camera_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.btn_rtmp1)
        self.rTMP2Label = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.rTMP2Label.setObjectName("rTMP2Label")
        self.from_camera_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.rTMP2Label)
        self.btn_rtmp2 = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.btn_rtmp2.setObjectName("btn_rtmp2")
        self.from_camera_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.btn_rtmp2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 791, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.menu_manage = QtWidgets.QAction(MainWindow)
        self.menu_manage.setObjectName("menu_manage")
        self.menu_add = QtWidgets.QAction(MainWindow)
        self.menu_add.setObjectName("menu_add")
        self.menu_login = QtWidgets.QAction(MainWindow)
        self.menu_login.setObjectName("menu_login")
        self.menu_quit = QtWidgets.QAction(MainWindow)
        self.menu_quit.setObjectName("menu_quit")
        self.menu.addAction(self.menu_add)
        self.menu.addAction(self.menu_login)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tab_action.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.gBox_action.setTitle(_translate("MainWindow", "操作"))
        self.tab_action.setTabText(self.tab_action.indexOf(self.tab_action_sample), _translate("MainWindow", "单设备"))
        self.tab_action.setTabText(self.tab_action.indexOf(self.tab_action_multi), _translate("MainWindow", "多设备"))
        self.gBox_list.setTitle(_translate("MainWindow", "列表"))
        self.gBox_info.setTitle(_translate("MainWindow", "信息"))
        self.Label_12.setText(_translate("MainWindow", "名称"))
        self.label_3.setText(_translate("MainWindow", "SN编号"))
        self.label_4.setText(_translate("MainWindow", "IP地址"))
        self.sDKLabel_2.setText(_translate("MainWindow", "SDK类型"))
        self.Label_7.setText(_translate("MainWindow", "登录名"))
        self.Label_8.setText(_translate("MainWindow", "密码"))
        self.Label_9.setText(_translate("MainWindow", "种类"))
        self.Label_10.setText(_translate("MainWindow", "品牌"))
        self.Label_11.setText(_translate("MainWindow", "型号"))
        self.rTMPLabel.setText(_translate("MainWindow", "RTMP流1"))
        self.btn_rtmp1.setText(_translate("MainWindow", "高清"))
        self.rTMP2Label.setText(_translate("MainWindow", "RTMP流2"))
        self.btn_rtmp2.setText(_translate("MainWindow", "普清"))
        self.menu.setTitle(_translate("MainWindow", "菜单"))
        self.menu_manage.setText(_translate("MainWindow", "设备管理"))
        self.menu_add.setText(_translate("MainWindow", "设备添加"))
        self.menu_login.setText(_translate("MainWindow", "登录"))
        self.menu_quit.setText(_translate("MainWindow", "退出"))

